# Generated by Django 6.0.1 on 2026-01-31 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mall', 'Shopping Mall'), ('office', 'Office Building'), ('lot', 'Parking Lot')], max_length=20)),
                ('address', models.TextField()),
                ('onboarding_type', models.CharField(choices=[('enterprise', 'Enterprise'), ('small', 'Small Business')], default='small', max_length=20)),
                ('confidence_score', models.IntegerField(default=80)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g., B1, P2, Ground', max_length=10)),
                ('floorplan_image', models.ImageField(blank=True, null=True, upload_to='floorplans/')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='atlas.facility')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('facility', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Spot identifier, e.g., A-101', max_length=20)),
                ('x', models.FloatField(help_text='X coordinate on floorplan')),
                ('y', models.FloatField(help_text='Y coordinate on floorplan')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Whether spot has been verified by installer')),
                ('distance_from_entry', models.IntegerField(default=0, help_text='Distance from entry in meters (for closest spot logic)')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='atlas.floor')),
            ],
            options={
                'ordering': ['distance_from_entry', 'code'],
                'unique_together': {('floor', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_code', models.CharField(max_length=50, unique=True)),
                ('bound_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='atlas.parkingspot')),
            ],
            options={
                'ordering': ['device_code'],
            },
        ),
    ]
