# Generated by Django 6.0.1 on 2026-01-31 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_type', 'device_code']},
        ),
        migrations.AddField(
            model_name='device',
            name='bound_facility',
            field=models.ForeignKey(blank=True, help_text='Facility entrance controlled by this barrier (barriers only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barriers', to='atlas.facility'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Parking Spot Sensor'), ('barrier', 'QR Boom Barrier')], default='sensor', help_text='Type of IoT device', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='bound_spot',
            field=models.OneToOneField(blank=True, help_text='Parking spot monitored by this sensor (sensors only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='atlas.parkingspot'),
        ),
    ]
