# Generated by Django 6.0.1 on 2026-01-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_alter_device_options_device_bound_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_code']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='bound_facility',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='bound_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='atlas.parkingspot'),
        ),
    ]
