# Generated by Django 6.0.1 on 2026-01-31 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_alter_device_options_remove_device_bound_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AddField(
            model_name='device',
            name='bound_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barriers', to='atlas.facility'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Parking Spot Sensor'), ('barrier', 'QR Boom Barrier')], default='sensor', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='bound_spot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='atlas.parkingspot'),
        ),
    ]
