# Generated by Django 6.0.1 on 2026-01-31 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_alter_device_options_device_bound_facility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily parking rate in INR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly parking rate in INR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Facility owner for P2P marketplace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facility',
            name='onboarding_type',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('small', 'Small Business'), ('p2p', 'Peer-to-Peer')], default='small', max_length=20),
        ),
    ]
