# Generated by Django 6.0.1 on 2026-01-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_facility_daily_rate_facility_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitute',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the facility', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the facility', max_digits=9, null=True),
        ),
    ]
