# Generated by Django 6.0.1 on 2026-01-31 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_user',
            field=models.ForeignKey(blank=True, help_text='Facility owner who needs to approve (for P2P)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='reserved', max_length=20),
        ),
    ]
